version: '2'
services:
  php:
    build: ./php
    volumes:
      - "./php/application/src:/var/www/src"
      - "./php/application/tests:/var/www/tests"
      - "./php/application/composer.json:/var/www/composer.json"
      - "./php/application/composer.lock:/var/www/composer.lock"
